-- meal_role bulk update — generated 2026-06-07 17:24:58
-- 699 recipes

BEGIN;

UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Adai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Adai with Avial';
UPDATE recipe_dna_master SET meal_role = '{side}' WHERE dish_name = 'Aloo Jeera';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Coastal Tamil Nadu' WHERE dish_name = 'Appam';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Coastal Tamil Nadu' WHERE dish_name = 'Appam and Coconut Milk';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Coastal Areas (e.g., Kerala influence in border regions)' WHERE dish_name = 'Appam with Vegetable Stew';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Ash Gourd and Lentil Rice';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarai Theeyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarakkai Kara Kulambu';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarakkai Kothu Porotta';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarakkai Puli Sadam';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarakkai Pulippu Sadam';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarakkai Saatham';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Karnataka' WHERE dish_name = 'Avarekai Akki Roti';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Karnataka' WHERE dish_name = 'Avarekai Bisibelebath';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Karnataka' WHERE dish_name = 'Avarekai Gojju';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Karnataka' WHERE dish_name = 'Avarekai Huli';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarekai Kichadi';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Karnataka' WHERE dish_name = 'Avarekai Majjige Huli';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarekai Pulao';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarekai Puliyodarai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Millet Based' WHERE dish_name = 'Bajra Adai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Millet Based' WHERE dish_name = 'Bajra Roti';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Flower and Drumstick Leaves Stir-fry';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Flower Rice';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Stem Adai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Stem and Coconut Payasam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Stem and Lentil Stew';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Stem Rice';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bangalore Brinjal Rice';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bangalore Style Brinjal Gothsu';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bangalore Style Mixed Vegetable Pulao';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bitter Gourd Aviyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bitter Gourd Mappillai Kathirikai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bitter Gourd Puli Sadam';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bitter Gourd Rice';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bitter Gourd Tamarind Rice';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bitter Gourd Theeyal';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Tamil Nadu (Brahmin Households)' WHERE dish_name = 'Brahmin Style Aviyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Brinjal and Lentil Stew';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Brahmin' WHERE dish_name = 'Brinjal Mappillai Kathirikai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Brahmin' WHERE dish_name = 'Capsicum and Curd Rice';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Madurai' WHERE dish_name = 'Capsicum and Groundnut Rice';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Thanjavur' WHERE dish_name = 'Capsicum and Lentil Pulao';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Capsicum and Paneer Masala';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Madurai' WHERE dish_name = 'Capsicum and Tamarind Rice';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Chettinad' WHERE dish_name = 'Cauliflower Biryani';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Cauliflower Flower Rice';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Cauliflower Pulao';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Cauliflower Semiya Upma';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Thanjavur' WHERE dish_name = 'Cauliflower Thayir Sadam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Aatukal Paya';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Eral Kulambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Eral Varuval';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Idiyappam';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Kari Dosa';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Kari Dosai (Chicken Keema Dosai)';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Kozhi Varuval';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Mutton Biryani';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Mutton Paya';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Nandu Masala';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Nandu Varuval';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Prawn Masala';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Vazhaipoo Poriyal';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Coastal' WHERE dish_name = 'Chicken Biryani';
UPDATE recipe_dna_master SET meal_role = '{side}' WHERE dish_name = 'Classic Paneer Butter Masala';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Coastal Style Prawn Varuval';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Thanjavur' WHERE dish_name = 'Egg Biryani';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Coastal' WHERE dish_name = 'Egg Dosa';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Chettinad' WHERE dish_name = 'Egg Idiyappam';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Brahmin' WHERE dish_name = 'Egg Kichadi';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Egg Kothu Dosa';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Madurai' WHERE dish_name = 'Egg Kothu Parotta';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Vellore' WHERE dish_name = 'Egg Kurma Dosa';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Egg Kuzhi Paniyaram';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Brahmin' WHERE dish_name = 'Egg Murukku Dosa';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Egg Muthar Dosai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Egg Omelette Adai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Salem' WHERE dish_name = 'Egg Omelette Dosa';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Egg Podi Dosai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Thanjavur' WHERE dish_name = 'Egg Pongal';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Coimbatore' WHERE dish_name = 'Egg Pulao';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Egg Puli Kuzhambu Rice';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Tirunelveli' WHERE dish_name = 'Egg Upma';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Egg Uthappam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Ennai Kathirikai (Stuffed Brinjal)';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Thanjavur / Brahmin' WHERE dish_name = 'Ennai Poli (Sweet)';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Eral Varuval';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Millet Based' WHERE dish_name = 'Foxtail Millet Dosa';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Idiyappam';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Idiyappam (Rice Noodles)';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Idli';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kambu Dosa';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kanchipuram' WHERE dish_name = 'Kanchipuram Idli';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Karaikudi Eral Varuval';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Karaikudi / Chettinad' WHERE dish_name = 'Karaikudi Prawn Fry';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Karamani Pulao';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Karamani Puli Kuzhambu Rice';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kathirikai Gothsu (Kongu Nadu Style)';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Millet Based' WHERE dish_name = 'Kodo Millet Kichadi';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Millet Based' WHERE dish_name = 'Kodo Millet Puttu';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongu Nadu Kari Dosa (Mutton Keema Dosa)';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongu Nadu Kari Dosai';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongu Nadu Urulai Roast With Idli';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongunadu Arisi Upma';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongunadu Chicken Varuval';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongunadu Kara Kozhambu';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongunadu Kari Dosa';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongunadu Kari Kozhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongunadu Kozhi Varuval';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongunadu Mutton Biryani';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongunadu' WHERE dish_name = 'Kongunadu Mutton Kari Dosai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongunadu Mutton Pulao';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongunadu' WHERE dish_name = 'Kongunadu Prawn Pulao';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongunadu Urulai Masala';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongunadu Varuval (Mutton Fry)';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Villages of Tamil Nadu' WHERE dish_name = 'Koozh';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kothavarangai Dosa';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kothavarangai Kuzhi Paniyaram Base';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kothavarangai Mappillai Kathirikai Masala';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kothavarangai Poriyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kothavarangai Poriyal (Cluster Beans Stir-fry)';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kothavarangai Puli Sadam';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kothavarangai Rice Pulao';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kothavarangai Sambar Rice';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kothavarangai Sambar Sadam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kothavarangai Theeyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Madurai' WHERE dish_name = 'Kothu Kari';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Madurai / Pan-Tamil Nadu' WHERE dish_name = 'Kothu Parotta';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Madurai' WHERE dish_name = 'Kothu Roti';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Kovai Meen Kulambu';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kovakkai Biryani';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kovakkai Masala Rice';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kovakkai Neer Vathal';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kovakkai Puli Sadam';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kovakkai Thair Sadam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kovakkai Theeyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kovakkai Varuval';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Millet Based' WHERE dish_name = 'Kuthiraivali Dosa';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Millet Based' WHERE dish_name = 'Kuthiraivali Pongal';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Millet Based' WHERE dish_name = 'Little Millet Kanji';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Madurai' WHERE dish_name = 'Madurai Chicken Kari Dosa';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Madurai' WHERE dish_name = 'Madurai Eraichi Varuval';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Madurai' WHERE dish_name = 'Madurai Kari Dosa';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Madurai' WHERE dish_name = 'Madurai Kozhi Varuval';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Madurai' WHERE dish_name = 'Madurai Meen Kulambu';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Madurai' WHERE dish_name = 'Madurai Mutton Biryani';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Madurai' WHERE dish_name = 'Madurai Mutton Kari Dosa';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Madurai' WHERE dish_name = 'Madurai Vecha Kozhi Varuval';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Meen Varuval';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Milagu Kozhambu';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Milagu Kuzhambu Rice';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Milagu Kuzhambu Sadam';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu / Rural Tamil Nadu' WHERE dish_name = 'Millet Dosa (Thinai Dosa)';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Mochai Beans Adai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Mochai Beans Pulao';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Mochai Puli Sadam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Mochai Varuval with Coconut';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Mullangi Dosai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Mullangi Pulao';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Mullangi Puli Sadam';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Mullangi Sambar Sadam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Mullangi Theeyal';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Murungakkai Masala Vada';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Murungakkai Milagu Pirattal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Murungakkai Pirattal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Murungakkai Poriyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Murungakkai Saaru';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Murungakkai Thokku';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Mutta Dosa';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Mutta Kuzhi Paniyaram';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Thanjavur' WHERE dish_name = 'Muttai Biryani';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Tirunelveli' WHERE dish_name = 'Muttai Kothu Parotta';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Madurai' WHERE dish_name = 'Muttai Omelette Masala';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Muttai Varuval';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Muttaik Dosai (Egg Dosa)';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Mutton Kari Dosai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Salem' WHERE dish_name = 'Mutton Keema Dosa';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Brahmin (also popular across Tamil Nadu)' WHERE dish_name = 'Mysore Pak';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Nandu Masala';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Coastal Tamil Nadu / Karnataka Border' WHERE dish_name = 'Neer Dosa';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Paal Appam';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Pattani Kootu Rice';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Pattani Masala Rice';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Pattani Pulao';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Pongal';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Pongal (Ven Pongal)';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Poosanikai Aviyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Poosanikai Payasam';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Poosanikai Sadam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Poosanikai Sambhar';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Poosanikai Theeyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Potato and Coconut Stew';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Prawn Masala';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Prawn Varuval';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Coastal Districts (especially Palakkad influenced areas)' WHERE dish_name = 'Puttu';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Millet Based' WHERE dish_name = 'Ragi Kali';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Rava Dosa';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Rava Idli';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Rava Pongal';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Rava Upma';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Banana and Lentil Stew';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Banana Fritters';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Banana Pulao';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Banana Puttu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Banana Stir-fry';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Mango Coconut Rice';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Mango Puli Sadam';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Mango Rice';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Salem' WHERE dish_name = 'Salem Chicken Biryani';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Salem' WHERE dish_name = 'Salem Chicken Kari Dosai';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Salem' WHERE dish_name = 'Salem Chicken Milagu Pirattal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Salem' WHERE dish_name = 'Salem Chicken Varuval';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Salem' WHERE dish_name = 'Salem Keema Varuval';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Salem' WHERE dish_name = 'Salem Mutton Biryani';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Salem' WHERE dish_name = 'Salem Mutton Kari Dosai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Salem' WHERE dish_name = 'Salem Mutton Pulao';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Salem' WHERE dish_name = 'Salem Prawn Varuval';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Salem' WHERE dish_name = 'Salem Style Keerai Masiyal';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Millet Based' WHERE dish_name = 'Samai Pongal';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Millet Based' WHERE dish_name = 'Samai Puttu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Yam Senai' WHERE dish_name = 'Senai Kizhangu Masiyal';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Tirunelveli' WHERE dish_name = 'Senai Kizhangu Puli Sadam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Senai Kizhangu Varuval';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Seppankizhangu Adai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Seppankizhangu Kuzhi Paniyaram';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Seppankizhangu Mappillai Kathirikai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Seppankizhangu Pulao';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Seppankizhangu Puli Sadam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Seppankizhangu Theeyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Seppankizhangu Varuval';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Millet Based' WHERE dish_name = 'Sirudhaniyam Dosa';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Snake Gourd Rice Pulao';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Puducherry' WHERE dish_name = 'Snake Gourd Semiya Upma';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Madurai' WHERE dish_name = 'Snake Gourd Tamarind Rice';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Snake Gourd Vegetable Stew';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Spiced Potato and Rice Flour Pancake';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Spicy Capsicum and Lentil Stew';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Chicken Kari Dosai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Kari Dosai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Kozhi Kulambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Meen Varuval';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Mutton Biryani';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Mutton Kari Dosai';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Prawn Fry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Prawn Varuval';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Rava Dosa';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Style Arisi Upma';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Style Kara Kozhambu';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Thali Dosai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Coastal' WHERE dish_name = 'Thengai Paal Biryani';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Coastal Areas (e.g., Nagapattinam, Ramanathapuram)' WHERE dish_name = 'Thengai Paal Dosa';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Thengai Paal Kurma';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Coastal' WHERE dish_name = 'Thengai Paal Puttu';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Thengai Paal Sadam';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Millet Based' WHERE dish_name = 'Thinai Idiyappam';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Millet Based' WHERE dish_name = 'Thinai Upma';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Chicken Biryani';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Chicken Varuval';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Erachi Varuval';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Eraichi Varuval';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Halwa Dosa';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Jigarthanda';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Kari Dosa';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Meen Varuval';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Mutton Biryani';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Mutton Kari Dosai';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Mutton Kulambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Nandu Varuval';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Prawn Fry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Prawn Varuval';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Seemai Halwa';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Sodhi';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Sodhi (Non-Veg Variation)';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Upma';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Urulai Kizhangu Kuzhi Paniyaram';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Urulai Kizhangu Mappillai Kathirikai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Urulai Kizhangu Podi Rice';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Urulai Kizhangu Pulao';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Urulai Kizhangu Sambar Rice';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Urulai Kizhangu Theeyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Urulai Roast';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Uthappam';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Millet Based' WHERE dish_name = 'Varagu Arisi Upma';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Millet Based' WHERE dish_name = 'Varagu Dosa';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Varuval Eraichi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Salem' WHERE dish_name = 'Vazhakkai Mappillai Kathirikai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Chettinad' WHERE dish_name = 'Vazhakkai Puli Sadam';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Vellore' WHERE dish_name = 'Vellore Chicken Kari Dosai';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Vellore' WHERE dish_name = 'Vellore Fish Kulambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Vellore' WHERE dish_name = 'Vellore Fish Varuval';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Vellore' WHERE dish_name = 'Vellore Mutton Kari Dosai';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Vellore' WHERE dish_name = 'Vellore Nandu Masala';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Kongu Nadu (Vellore influence)' WHERE dish_name = 'Vellore Style Kongu Nadu Mutton Biryani';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Vellore' WHERE dish_name = 'Vellore Vecha Kozhi Varuval';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Brahmin' WHERE dish_name = 'Ven Pongal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Virudhunagar' WHERE dish_name = 'Virudhunagar Kandha Pasalai';
UPDATE recipe_dna_master SET meal_role = '{main}', sub_region = 'Virudhunagar' WHERE dish_name = 'Virudhunagar Kari Dosa';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Virudhunagar' WHERE dish_name = 'Virudhunagar Nandu Varuval';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Arachuvitta Kathirikkai Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Madurai' WHERE dish_name = 'Arachuvitta Poondu Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Arachuvitta Sambar';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Ash Gourd and Coconut Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Ash Gourd and Coconut Poriyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Ash Gourd and Drumstick Sambar';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Ash Gourd and Lentil Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Ash Gourd and Lentil Sundal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Ash Gourd and Spinach Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Ash Gourd and Yogurt Raita';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Ash Gourd Dal Rasam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Ash Gourd Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Ash Gourd Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarakkai Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarakkai Mor Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarakkai Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarakkai Poriyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarakkai Pulippu Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarakkai Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarakkai Vada Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarakkai Vadam Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarakkai Vathal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarakkai Vathal Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarekai Aviyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarekai Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarekai Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarekai Poriyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarekai Puli Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarekai Rasam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarekai Sundal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Avarekai Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Aviyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Flower and Coconut Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Flower and Coconut Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Flower and Drumstick Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Flower and Groundnut Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Flower and Lentil Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Flower and Lentil Sundal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Flower and Ridge Gourd Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Flower and Spinach Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Flower and Yam Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Flower Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Flower Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Flower Poriyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Flower Rasam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Stem and Drumstick Puli Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Stem and Drumstick Sambar';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Stem and Moong Dal Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Stem and Peanut Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Stem and Yam Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Stem Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Stem Rasam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Stem Salad with Spiced Yogurt';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Stem Stir-fry with Coconut';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Stem Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Banana Stem Thoran';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bangalore Brinjal Aviyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bangalore Brinjal Chutney Rice';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bangalore Brinjal Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bangalore Brinjal Mor Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bangalore Brinjal Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bangalore Brinjal Poriyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bangalore Brinjal Puli Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bangalore Brinjal Rasam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bangalore Brinjal Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bangalore Brinjal Vathal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bangalore Brinjal Vathal Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bitter Gourd Chips';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bitter Gourd Fry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bitter Gourd Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bitter Gourd Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bitter Gourd Paal Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bitter Gourd Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bitter Gourd Rasam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bitter Gourd Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Bitter Gourd Vathal Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Brahmin Style Sambar';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Brahmin (common across Tamil Nadu but distinct style)' WHERE dish_name = 'Brahmin Style Vada Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Brinjal and Coconut Milk Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Brinjal and Drumstick Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Brinjal and Peanut Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Madurai' WHERE dish_name = 'Brinjal and Yam Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Brinjal Podi Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Brinjal Vathal Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Capsicum and Coconut Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Capsicum and Coconut Milk Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Capsicum and Coconut Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Capsicum and Drumstick Leaves Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Capsicum and Lentil Salad';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Capsicum and Peanut Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Madurai' WHERE dish_name = 'Capsicum Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Brahmin' WHERE dish_name = 'Capsicum Rasam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Cauliflower and Coconut Sundal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Cauliflower Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Cauliflower Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Brahmin' WHERE dish_name = 'Cauliflower Mor Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tanjore' WHERE dish_name = 'Cauliflower Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Cauliflower Paruppu Urundai Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Cauvery Delta' WHERE dish_name = 'Cauliflower Poriyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Madurai' WHERE dish_name = 'Cauliflower Puli Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Brahmin' WHERE dish_name = 'Cauliflower Rasam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal Tamil Nadu' WHERE dish_name = 'Cauliflower Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Cauliflower Vathal Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Chicken Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Eral Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Eral Vada Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Karaikudi Vatha Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Kathirikai Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Kozhi Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Kozhi Milagu Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Kozhi Rasam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Meen Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad / Coastal' WHERE dish_name = 'Chettinad Meen Kuzhambu (Fish Curry)';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Mutton Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Mutton Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Chettinad Nandu Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}' WHERE dish_name = 'Chicken Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Chowli Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Cluster Beans and Coconut Stir-fry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Cluster Beans and Coconut Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Cluster Beans and Drumstick Leaves Stir-fry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Cluster Beans Aviyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Cluster Beans Dal Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Cluster Beans Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Cluster Beans Paal Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Cluster Beans Poriyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Cluster Beans Vathal Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Coastal Style Eral Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal Tamil Nadu' WHERE dish_name = 'Coastal Style Fish Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal Areas' WHERE dish_name = 'Coastal Style Meen Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Coastal Style Prawn Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Crab Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Crispy Potato Fritters';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Drumstick and Coconut Raita';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Drumstick and Peanut Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Drumstick and Ridge Gourd Thoran';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Drumstick and Tomato Rasam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Drumstick and Yam Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Drumstick Aviyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Drumstick Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Drumstick Flower Fritters';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Drumstick Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Drumstick Leaves and Coconut Stir-fry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Drumstick Leaves and Garlic Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Drumstick Leaves Stir-fry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Drumstick Mor Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Brahmin' WHERE dish_name = 'Drumstick Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Drumstick Podi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Drumstick Podi Poriyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Drumstick Puli Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Drumstick Rasam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Drumstick Tendrils and Garlic Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal Tamil Nadu' WHERE dish_name = 'Drumstick Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Drumstick Vathal Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Egg Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Egg Milagu Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Egg Omelette Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Egg Podimas';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Egg Puli Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Ennai Kathirikkai (Tamil Nadu Style Brinjal Curry)';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Eral Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Fish Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Homestyle Dal Tadka';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Idli and Sambar';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Idli with Coconut Chutney and Sambar';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kara Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Karaikudi Mutton Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Kathirikai Kara Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Brahmin' WHERE dish_name = 'Kathirikai Mor Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Kathirikai Perum Kaai Kara Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Kathirikai Poriyal (Chettinad Style)';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Madurai' WHERE dish_name = 'Kathirikai Puli Kuzhambu (Madurai Style)';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Kathirikai Thokku';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Kathirikai Vathal Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Kathirikkai Gothsu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tanjore' WHERE dish_name = 'Kathirikkai Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kathirikkai Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kathirikkai Poriyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Salem' WHERE dish_name = 'Keerai Masiyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongu Nadu Urulai Roast (Potato Roast)';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongu Nadu Vada Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongunadu Chicken Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongunadu Kozhi Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongunadu Meen Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongunadu Mutton Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongunadu Nandu Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongunadu Poondu Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongunadu Urulai Mutton Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kongunadu Urulai Roast';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kothavarangai Arachuvitta Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kothavarangai Brinjal Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kothavarangai Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kothavarangai Poricha Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kothavarangai Puli Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kothavarangai Vatha Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kovakkai Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kovakkai Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kovakkai Poriyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kovakkai Puli Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Kovakkai Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kovakkai Vatha Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Kozhi Milagu Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur & Delta Regions' WHERE dish_name = 'Kozhukattai';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Kuzhambu Vella Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kuzhambu Vendaikai (Okra Curry)';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Kuzhambu Vendaikkai';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Kuzhi Paniyaram (Savory)';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Kuzhi Paniyaram (Sweet)';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal Areas (Chennai)' WHERE dish_name = 'Madras Fish Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Madras (Chennai)' WHERE dish_name = 'Madras Puli Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Madras' WHERE dish_name = 'Madras Vegetable Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Madurai' WHERE dish_name = 'Madurai Eraichi Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Madurai' WHERE dish_name = 'Madurai Jallikattu Mutton Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Madurai' WHERE dish_name = 'Madurai Jigarthanda';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Madurai' WHERE dish_name = 'Madurai Jigarthanda (as a breakfast drink)';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Madurai' WHERE dish_name = 'Madurai Kozhi Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Madurai' WHERE dish_name = 'Madurai Meen Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Madurai' WHERE dish_name = 'Madurai Nandu Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Madurai' WHERE dish_name = 'Madurai Style Sundakkai Vatha Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Milagu Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Mochai Field Beans Tamil Nadu' WHERE dish_name = 'Mochai Beans and Coconut Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Mochai Field Beans Tamil Nadu' WHERE dish_name = 'Mochai Beans and Drumstick Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Mochai Field Beans Tamil Nadu' WHERE dish_name = 'Mochai Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Mochai Field Beans Tamil Nadu' WHERE dish_name = 'Mochai Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Mochai Field Beans Tamil Nadu' WHERE dish_name = 'Mochai Payaru Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Mochai Field Beans' WHERE dish_name = 'Mochai Payaru Poriyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Mochai Field Beans' WHERE dish_name = 'Mochai Payir Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Mochai Field Beans Tamil Nadu' WHERE dish_name = 'Mochai Varuval';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Mochai Field Beans' WHERE dish_name = 'Mochai Vathal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Moor Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Mullangi Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Mullangi Paal Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Mullangi Vada Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Mullangi Vatha Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Murungakkai Kothu Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Murungakkai Masala Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Murungakkai Paal Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Murungakkai Puli Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Murungakkai Sambar';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Murungakkai Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Murungakkai Vatha Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Mutta Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Mutton Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Mutton Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Nandu Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Nenju Elumbu Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Nenju Elumbu Kuzhambu (Mutton Bone Marrow Curry)';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Nethili Meen Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Panchapoorna Vadai';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Paruppu Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Paruppu Urundai Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Paruppu Usili';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Pattani Vada Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal Areas (Pondicherry)' WHERE dish_name = 'Pondicherry Style Fish Curry (Meen Kuzhambu)';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Poondu Vatha Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Poosanikai Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Poosanikai Morkuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Poosanikai Puli Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Poosanikai Vatha Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Poricha Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Potato and Coconut Stir-fry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Potato and Drumstick Podi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Potato and Lentil Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Potato and Peanut Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Potato and Ridge Gourd Stir-fry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Potato and Tomato Rasam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Prawn Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Puli Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Puliyodarai Mix';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Radish and Coconut Stir-fry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Radish and Drumstick Leaves Poriyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Radish and Lentil Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Radish and Yogurt Raita';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Radish Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Radish Rasam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Radish Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Rasam (Milagu Rasam)';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Banana and Drumstick Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Banana and Drumstick Stir-fry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Banana and Peanut Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Banana Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Banana Kofta Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Banana Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Banana Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Banana Thoran';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Banana Vada';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Banana Vada Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Mango and Coconut Stir-fry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Mango and Coconut Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Mango and Drumstick Leaves Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Mango and Lentil Salad';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Mango Brinjal Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Mango Dal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Mango Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Mango Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Mango Rasam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Mango Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Raw Mango Vendakkai Puli Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Ridge Gourd and Lentil Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Salem' WHERE dish_name = 'Salem Mutton Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Salem' WHERE dish_name = 'Salem Mutton Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Salem' WHERE dish_name = 'Salem Nandu Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Salem' WHERE dish_name = 'Salem Style Chicken Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Salem' WHERE dish_name = 'Salem Style Mutton Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Senai Kizhangu Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Senai Kizhangu Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Senai Kizhangu Mor Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Senai Kizhangu Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Senai Kizhangu Podi Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Senai Kizhangu Poriyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Senai Kizhangu Puli Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Senai Kizhangu Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Senai Kizhangu Vathal Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Seppankizhangu Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Seppankizhangu Masala Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Seppankizhangu Masiyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Seppankizhangu Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Seppankizhangu Poriyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Seppankizhangu Rasam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Seppankizhangu Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Seppankizhangu Vatha Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Brahmin' WHERE dish_name = 'Snake Gourd and Yam Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Snake Gourd Aviyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tanjore' WHERE dish_name = 'Snake Gourd Coconut Milk Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Brahmin' WHERE dish_name = 'Snake Gourd Dal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Puducherry' WHERE dish_name = 'Snake Gourd Dal Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Snake Gourd Drumstick Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Snake Gourd Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Snake Gourd Lentil Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Puducherry' WHERE dish_name = 'Snake Gourd Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Snake Gourd Poriyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Snake Gourd Puli Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Snake Gourd Rasam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Snake Gourd Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Spiced Capsicum Sundal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Spiced Potato Mash';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Spiced Potato Salad';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Spicy Brinjal Fry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Spicy Capsicum and Brinjal Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Spicy Capsicum Stir-fry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Tamarind and Drumstick Leaves Rasam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Arachu Vitta Kathirikkai Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Arachu Vitta Mutton Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Chettinad Chicken Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Chicken Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Chicken Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Fish Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Fish Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Meen Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Mutton Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Prawn Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Style Arachu Vitta Sambar';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Style Brinjal Curry (Kathirikai Kuzhambu)';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur / Coastal' WHERE dish_name = 'Thanjavur Style Prawn Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Thanjavur Style Sambar';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Thengai Paal Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Thengai Paal Rasam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Thengai Rasam';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Thengai Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Thogayal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Alwa';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Chicken Kola Urundai Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Chicken Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Chicken Milagu Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Erachi Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Eraichi Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Fish Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Fish Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Macaroon';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Meen Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Mutton Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Nandu Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Prawn Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Tirunelveli Seepu Seedai';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Brahmin' WHERE dish_name = 'Ulundhu Vadai';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Urulai Kizhangu Kara Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Urulai Kizhangu Masala Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Urulai Kizhangu Vathal Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Uthukuli Vada Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Vada Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Vanjaram Meen Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Vazhaipoo Vadai';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Vazhakkai Poriyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Brahmin' WHERE dish_name = 'Vazhakkai Varuval';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Thanjavur' WHERE dish_name = 'Vella Paniyaram';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Vellore' WHERE dish_name = 'Vellore Fish Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Vellore' WHERE dish_name = 'Vellore Meen Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Vellore' WHERE dish_name = 'Vellore Mutton Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Vellore' WHERE dish_name = 'Vellore Prawn Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal Areas (Vellore influence)' WHERE dish_name = 'Vellore Style Fish Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Vellore' WHERE dish_name = 'Vellore Style Mutton Curry';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Vellore / North Arcot' WHERE dish_name = 'Vellore Style Vegetable Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Kongu Nadu' WHERE dish_name = 'Vendaikkai Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Chettinad' WHERE dish_name = 'Vendaikkai Puli Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Vendakkai Pachadi';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Tirunelveli' WHERE dish_name = 'Vendakkai Poricha Kootu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Pan-Tamil Nadu' WHERE dish_name = 'Vendakkai Poriyal';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Coastal' WHERE dish_name = 'Vendakkai Puli Kuzhambu';
UPDATE recipe_dna_master SET meal_role = '{side}', sub_region = 'Villupuram District (Northern Tamil Nadu)' WHERE dish_name = 'Villu Puram Style Rasam (Poondu Rasam)';
UPDATE recipe_dna_master SET meal_role = '{side}' WHERE dish_name = 'White Gravy Paneer';

-- Verify
SELECT meal_role, COUNT(*) FROM recipe_dna_master GROUP BY meal_role ORDER BY meal_role;

COMMIT;